version: "3.7"
services:
  mongo:
    image: mongo:4.2-rc
    restart: always
    ports:
      - 27017:27017
    env_file:
      - mongo-dev.env
    volumes:
      - ${PWD}/mongo/db:/data/db
    container_name: mongo-docker
    networks:
      - mongo

networks:
  mongo:
    driver: bridge
